name: CivChat
main: com.untamedears.civchat.CivChat
version: 0.95
authors: [Rourke750, ibbignerd]
commands:
   tell:
      description: Sends a player a message.
      usage: /<command> <player> <message>
      aliases: [message, msg, m, pm]
   exit:
      description: Exits personal message channel with player.
      usage: /exit
   civchat:
      description: Command for loading/saving config.
      usage: /<command> <subcommand>
      permission: civchat.admin
   groupchat:
      description: Command for talking to Citadel Groups.
      usage: /<command> <group> <message>
      aliases: [g, group]
   chat:
      description: Command for helping players understand CivChat
      usage: /<command> <subcommand>
      aliases: [chathelp, ch]
   reply:
      description: Reply to the last player who was messaged
      usage: /<command> <message>
      aliases: r
permissions:
   civchat.admin:
      description: Admin commands for civchat.
      default: op